#!/bin/sh
#
# $File: ${DOTDIR}/system/alias
# $Date: 2011-09-07T23:31:15+0900$
# vim:filetype=sh:tabstop=2:shiftwidth=2:fdm=marker:

alias cp="cp -i"
alias mv="mv -i"
alias rm="rm -i"
alias rr="rm -rf"
alias mkdir="mkdir -p"
alias df="df -kTh"
alias du="du -kh"
alias history="fc -l 1"
alias more="less"
alias where="command -v"
alias pd="pushd"
alias po="popd"
alias su="su -l"
alias _="sudo"
alias 644='chmod 644'
alias 755='chmod 755'
alias gd='dirs -lv; echo -n "select number: "; read newdir; cd +"$newdir"'
alias utf='export LANG=ja_JP.UTF-8; export LANGUAGE=ja_JP.UTF-8; export LC_ALL=ja_JP.UTF-8'
alias en='export LANG=en; export LANGUAGE=en; export LC_ALL=en'
alias eucjp='export LANG=ja_JP.eucJP; export LANGUAGE=ja_JP.eucJP; export LC_ALL=ja_JP.eucJP'
alias sjis='export LANG=ja_JP.SJIS; export LANGUAGE=ja_JP.SJIS; export LC_ALL=ja_JP.SJIS'
