#!/usr/bin/sh
#
# $File: ${DOTDIR}/system/ostype
# $Date: 2011-09-10T03:42:41+0900$
# vim:filetype=sh:tabstop=2:shiftwidth=2:fdm=marker:

function is_linux() {
  [[ $OSTYPE == linux* ]] && return 0
  return 1
}

function is_solaris() {
  [[ $OSTYPE == solaris* ]] && return 0
  return 1
}

function is_darwin() {
  [[ $OSTYPE == darwin* ]] && return 0
  return 1
}

function is_cygwin() {
  [[ $OSTYPE == cygwin* ]] && return 0
  return 1
}

