#!/usr/bin/sh
#
# $File: ${DOTDIR}/system/ostype
# $Date: 2011-09-09T23:39:59+0900$
# vim:filetype=sh:tabstop=2:shiftwidth=2:fdm=marker:

if [ -x "/usr/bin/uname" ] || [ -x "/bin/uname" ]; then
  case `uname -s` in
    Linux*)   OSTYPE=Linux ;;
    Solaris*) OSTYPE=Solaris ;;
    Darwin*)  OSTYPE=Darwin ;;
    CYGWIN*)  OSTYPE=Cygwin ;;
    *) ;;
  esac
fi

is_linux(){
  [[ $OSTYPE == Linux ]] && return 0
  return 1
}
is_solaris(){
  [[ $OSTYPE == Solaris ]] && return 0
  return 1
}
is_darwin(){
  [[ $OSTYPE == Darwin ]] && return 0
  return 1
}
is_cygwin(){
  [[ $OSTYPE == Cygwin ]] && return 0
  return 1
}

