#!/usr/bin/sh
#
# $File: ${DOTDIR}/system/path
# $Date: 2011-09-11T21:41:13+0900$
# vim:filetype=sh:tabstop=2:shiftwidth=2:fdm=marker:


if [ -d ${HOME}/bin ]; then
  export PATH=$PATH:$HOME/bin
fi

if [ -d ${DOTDIR}/bin ]; then
  export PATH=$PATH:$DOTDIR/bin
fi


if [[ $OSTYPE == darwin* ]]; then

  if [ -d /Developer/usr/bin ]; then
    export PATH=$PATH:/Developer/usr/bin
  fi
fi
