#!/usr/bin/sh
#
# $File: ${DOTDIR}/system/path
# $Date: 2011-09-12T11:50:05+0900$
# vim:filetype=sh:tabstop=2:shiftwidth=2:fdm=marker:


if [ -d ${HOME}/bin ]; then
  export PATH=$PATH:$HOME/bin
fi

if [ -d ${DOTDIR}/bin ]; then
  export PATH=$PATH:$DOTDIR/bin
fi

if [[ $OSTYPE == darwin* ]]; then
  if [ -d /Developer/usr/bin ]; then
    export PATH=$PATH:/Developer/usr/bin
  fi
  if [ -f /usr/local/lib/pkgconfig ]; then
    export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
  fi
fi
