APP		 = $(shell basename $(CURDIR))
SYMLINKS = keymap.conf \
		   azik-supp.rule zw.rule \
		   AquaSKK-Hirakana.png \
		   AquaSKK-Katakana.png \
		   AquaSKK-Jisx0201Kana.png \
		   AquaSKK-Ascii.png \
		   AquaSKK-Jisx0208Latin.png \
		   Mini-Hirakana.png \
		   Mini-Katakana.png \
		   Mini-Jisx0201Kana.png \
		   Mini-Ascii.png \
		   Mini-Jisx0208Latin.png
PREFIX	= $(HOME)/Library/Application\ Support/$(APP)

include ../../../Makefile.rule
