APP		 = $(shell basename $(CURDIR))
SYMLINKS = keymap.conf azik-supp.rule zw.rule
FILES	 = AquaSKK-Hirakana.png AquaSKK-Katakana.png AquaSKK-Jisx0201Kana.png AquaSKK-Ascii.png AquaSKK-Jisx0208Latin.png
PREFIX	 = $(HOME)/Library/Application\ Support/$(APP)

include ../../../Makefile.rule
